name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Build and test
      run: |
        # Здесь должны быть команды для сборки и тестирования вашего приложения
    - name: Доставка на сервер
      uses: some-deployment-action@v1
      with:
        server: example.com
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
      # Другие настройки для доставки приложения на сервер


